name: myenv_ray

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - ccache
  - cmake
  - cudatoolkit=11.0
  - cudnn=8.0
  - cxx-compiler
  - jupyterlab
  - jupyter
  - notebook
  - pip
  - pip:
      - tensorflow-gpu==2.4.*
      - ray[default]
      - ray[rllib]
      - gputil
  - python=3.8
  - pytorch=1.7
  - tensorboard=2.4
  - torchaudio
  - torchvision
  - scikit-learn
  - matplotlib
  - pandas
  - seaborn
  - tqdm
  - networkx
  - scipy
